### ISSUE TITLE
"Open in a new page" not saved when exporting

### ISSUE THREAD

**Issue by CIFOM** [davosmith/moodle-checklist#105]
Hi Davo,
Your plugin is the one I use the most because I can accurately follow the student's progress in real time.
Thank you for this work.
I noticed an issue and a suggested improvement. So I send two Git-Issues.
Often, I put a link for a CheckList Task, and check the "Open in a new page" option.
Unfortunately, when exporting the course and re-importing, the "Open in a new page" checkbox is reset to false.
I noticed that the checkbox state is not included in the checklist.xml contained in the MBZ file.
This appears only in the mbz file. The export/import function is working fine.
Regards
Alain / CIFOM

**Comment by davosmith** [comment]
Looks like backup support was missing in the patch I was sent a few years back.

Should be a really quick fix, but I'm not going to be able to look at it before the weekend.

**Comment by CIFOM** [comment]
Yeah! Thanks.

**Comment by davosmith** [comment]
I've just pushed a fix to this. Please can you confirm that the new version here on github is working as expected?

**Comment by CIFOM** [comment]
Hi Davo,
Thank you for the fix. It works! I guess it will be helpfull for the other teachers too!
Have a nice day.
