### ISSUE TITLE
Double tick box, selection issues and  progress bar not updating

### ISSUE THREAD

**Issue by kiratskitizing** [davosmith/moodle-checklist#108]
Using mod_checklist version 2023041400
1. Create a course and enrol a student.
2. Turn edit mode to On.
3. Add a Checklist activity set updates to "Student and Teacher"
4. Go to the Checklist activity and add three items.
5. Log in as student user and visit checklist.
RESULT:
You will see what appears to be "double tick-box", but only one can be ticked.
![image](https://github.com/davosmith/moodle-checklist/assets/16247613/dcd2f775-f6d4-4fd1-b2e8-77923562b68b)
6. Still as student, tick two items.
7. RESULT:
You will notice that the progress bar does not update. 
![image](https://github.com/davosmith/moodle-checklist/assets/16247613/a9286ddf-4d7a-4267-8c31-79a19fc249d2)
8. As teacher/admin, update checklist setting "Updates by" = Student Only.
9. Back as student, refresh the page.
RESULT: Notice the double tick box is removed, and progress bar is updated
![image](https://github.com/davosmith/moodle-checklist/assets/16247613/60e83031-bc95-45c7-bf15-20a05faf0ae5)
10 As teacher/admin, update checklist setting "Updates by" = Teacher Only
11. As teacher (with capability mod/checklist:updateown = Allow), go to the checklist activity, notice you can not select anything at all
![image](https://github.com/davosmith/moodle-checklist/assets/16247613/8a138877-84c5-443e-b6c2-57230bcbbe8f)

**Comment by davosmith** [comment]
Everything you have described above looks to be working exactly as described:

- When student + teacher marking is enabled, 2 checkboxes are shown - 1 for the student to mark-off, 1 showing which items the teacher has marked off (as you would expect, the student is not able to change the status of the teacher checkbox). If you hover your mouse over the teacher checkbox, the help text will state that "Teacher has not yet marked this"
- When both student and teacher marking is enabled, the progress bar reflects the status of the _teacher_ marks, not the marks that the student has given themselves (I cannot think of a way that a single progress bar can show both at the same time, so it is assumed that the teacher's mark is the more authoritative).
- Switching to 'student only' is working exactly as you would expect (the teacher checkboxes are no longer shown, the progress bar now reflects the mark given by the student)
- Switching to 'teacher only', then viewing the 'student' view of the checklist (whether as a student or a teacher) is exactly as expected - there is no way to update the teacher mark status from that view (I'm not sure how that would be helpful anyway - from that view, the teacher would only be able to update the 'teacher' status for their own checklist, not that of any of their students).
- If you want to update the 'teacher' state for any of the checklist items, simply click on '**View progress**' in the tabs at the top of the page, then either:
  - Click on '**Edit checks**' and update the states for multiple students at once OR
  - Click on the '**View progress for this user**' icon (beside the student's name) and update the teacher marks for that individual student
