### ISSUE TITLE
Completion rules missing new suffix

### ISSUE THREAD

**Issue by opitz** [davosmith/moodle-checklist#110]
From version 4.3 Moodle needs to append a suffix to completion rules (https://moodledev.io/docs/4.3/devupdate#append-a-suffix-to-the-completion-rules).
Missing these results in being removed from the Default activity completion form.

**Comment by davosmith** [comment]
Thanks for the heads-up. I'd not spotted this.

I'll see if I can figure out the changes needed over the weekend.
