### ISSUE TITLE
There is an exception in the Moodle 4.1 

### ISSUE THREAD

**Issue by bbdev2** [davosmith/moodle-checklist#114]
plugin version: 3.9.4.0 (2024012000)

In mod/checklist/classes/external/update_item_state.php classes were used from libdir/externallib.php:
use core_external\external_api;
use core_external\external_value;
use core_external\external_function_parameters;
use core_external\external_single_structure;

it's a wrong usage, because in the moodle 4.1 they hadn't been moved to core_external package yet. All classes in lib.php must be used with leading \ symbol without the core_external package.

By this reason your plugin doesn't support moodle 4.1 and below. Please make correct the plugin description in https://moodle.org/plugins/mod_checklist/versions .

Thank you!

**Comment by davosmith** [comment]
As far as I can see, this will only affect the new Moodle mobile app functionality (which is the only place where this function is called.

It should be fairly simple to update the code to fix this and push out an updated version, so there shouldn't be any reason to update the description in the Moodle plugins directory.

**Comment by davosmith** [comment]
@bbdev2 there is now a fix here on github - are you able to confirm that this solves the problem?

If so, I will push a new version out to the Moodle plugins directory.

**Comment by davosmith** [comment]
OK - fair enough. There is a fix here now, can you confirm that it solves the problem?

**Comment by bbdev2** [comment]
not yet, i'll check it later

**Comment by bbdev2** [comment]
yes, all is correct now. TY

**Comment by davosmith** [comment]
Thanks for checking - I've pushed a new release out to the Moodle plugins directory. Apologies for the bug in the first place - I'd missed that when reviewing the code that I was sent for the mobile app.
