### ISSUE TITLE
MySQL 8.01 and "GROUPING"

### ISSUE THREAD

**Issue by dustinbrisebois** [davosmith/moodle-checklist#115]
As per https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-8-0-detailed-G

MySQL reserves the keyword "GROUPING" 

We are seeing some use cases of mod_checklist throwing SQL formatting errors

 One easy solution is in ~ locallib.php#2660

make the line:

`$select = "checklist = :id AND 
userid = 0 AND 
itemoptional = ".CHECKLIST_OPTIONAL_NO." AND 
hidden = ".CHECKLIST_HIDDEN_NO." AND 
{checklist_item}.$groupingsql";`

AND (same file on ~ 2742)

`
    public static function get_grouping_sql($userid, $courseid, $prefix = '') {
        $groupings = self::get_user_groupings($userid, $courseid);
        if ($groupings) {
            $groupings[] = 0;
            **$groupingsql = "{$prefix}grouping IN (".implode(',', $groupings).') ';**
        } else {
            **$groupingsql = "{$prefix}grouping = 0 ";**
        }
        return $groupingsql;
    }
`

Removing the preceeding SPACE on the concatenation thereby making the reserved keyword mute.

**Comment by davosmith** [comment]
Please can you check you are using the latest code - the lines of code you have suggested changing were fixed nearly 5 years ago to work with MySQL 8 (the term 'grouping' has been replaced by 'groupingid' in all places).

**Comment by davosmith** [comment]
mod_checklist is kept up to date for versions right back to Moodle 3.9 (which itself is now nearly 4 years old and dropped out of support in December) - if you're not even on Moodle 3.9, then I'd suggest that upgrading to a supported version of Moodle should be your top priority at the moment.

I've just double-checked and the Moodle 3.4 - 3.8 version of mod_checklist also has the fix, so you must be using an even older version of Moodle than I'd first realised.

If you need checklist to work until you are able to upgrade, then you should be able to apply this fix to your local version, but I cannot promise it will fully work: https://github.com/davosmith/moodle-checklist/commit/e2920284d82cb3b60947a8556e6cfab44d51bcea
