### ISSUE TITLE
Using deprecated Behat test step with Moodle 4.4dev

### ISSUE THREAD

**Issue by opitz** [davosmith/moodle-checklist#118]
I get this issue:

And I add a "Checklist" to section "1" and I fill the form with:: Deprecated step, rather than using this step you can:
- behat_course::i_add_to_course_section_and_i_fill_the_form_with
- Set $CFG->behat_usedeprecated in config.php to allow the use of deprecated steps
                    if you don't have any other option (Exception)

**Comment by synergylearning-github** [comment]
Thanks for the heads-up - I'll be testing the checklist plugin against 4.4, once it reaches release candidate stage and will fix any issues found at that stage.

**Comment by davosmith** [comment]
And I really should check which github account I'm signed-in with, before replying to tickets ...
