### ISSUE TITLE
Moodle 4.3 final deprecation of *_get_completion_state() callbacks

### ISSUE THREAD

**Issue by marcestone** [davosmith/moodle-checklist#121]
Hi!
I found that in https://github.com/davosmith/moodle-checklist/blob/master/lib.php#L923, the `checklist_get_completion_state` function is still declared in the latest version. According to the Moodle Tracker ticket https://tracker.moodle.org/browse/MDL-71196, the *_get_completion_state() callbacks were deprecated and are being replaced by the activity custom completion classes.
Here it is how the callbacks were replaced in multiple Moodle Core plugins: https://github.com/moodle/moodle/commit/334b6c75a43ea2a72995d14ee9526e6b82662270.

**Comment by davosmith** [comment]
If you look at the link you provided to the function in my code, you will note the comment immediately above it "Retained for compatibility with Moodle 3.10 and below.".

You should also note that the new API is also already supported by mod_checklist (and has been for a couple of years).

Therefore there is nothing for me to do here (I may clean up the old code at some point in the future).

**Comment by marcestone** [comment]
Right. Thanks @davosmith for the clarification.
