### ISSUE TITLE
Error occurs when adding new Checklist and including whole class

### ISSUE THREAD

**Issue by MUSLonas** [davosmith/moodle-checklist#122]
The following error displays when I create a new checklist with the whole course included. Do you have any ideas as to what might be causing the issue?

System is running PHP 8.0.

Exception - mysqli::real_escape_string(): Argument #1 ($string) must be of type string, array given
[More information about this error](https://docs.moodle.org/401/en_us/error/moodle/generalexceptionmessage)
Debug info:
Error code: generalexceptionmessage×Dismiss this notification
Stack trace:
line 1149 of /lib/dml/mysqli_native_moodle_database.php: TypeError thrown
line 1149 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli->real_escape_string()
line 1216 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->emulate_bound_params()
line 1402 of /lib/dml/moodle_database.php: call to mysqli_native_moodle_database->get_recordset_sql()
line 78 of /admin/tool/log/store/standard/classes/log/store.php: call to moodle_database->get_recordset_select()
line 299 of /mod/checklist/classes/local/autoupdate.php: call to logstore_standard\log\store->get_events_select()
line 204 of /mod/checklist/classes/local/autoupdate.php: call to mod_checklist\local\autoupdate::get_logged_userids_new()
line 3015 of /mod/checklist/locallib.php: call to mod_checklist\local\autoupdate::get_logged_userids()
line 559 of /mod/checklist/locallib.php: call to checklist_class->update_all_autoupdate_checks()
line 146 of /mod/checklist/locallib.php: call to checklist_class->update_items_from_course()
line 61 of /mod/checklist/view.php: call to checklist_class->__construct()

**Comment by K1Yuhh** [comment]
Exception - mysqli::real_escape_string(): Argument #1 ($string) must be of type string, array given.

It expects a string and you are passing an array. Could you please show us the paramter you're passing in the mysqli_real_escape_string function.

**Comment by davosmith** [comment]
Odd that this hasn't been an issue before - apart from a few minor layout changes, the logic of that file hasn't really changed in years.

@K1Yuhh I cannot tell you exactly what is being passed into real_escape_string(), as my code isn't calling that function - it is calling get_recordset_select(), which, eventually, results in a call to real_escape_string() deep inside the Moodle core code.

I think, however, I can see the problem and will see if I can put together a fix for it.

**Comment by davosmith** [comment]
I've pushed a fix - various automated checks are running at the moment.

Assuming they all pass, I will update the version number and publish a new release in the morning (UK time).

If you need the fix quicker than that, you can get the latest code from this github repository (the 'master' branch for Moodle 4.1 or above, the MOODLE_39_STABLE branch for Moodle 3.9-4.0).

**Comment by davosmith** [comment]
The fix is now deployed to the Moodle plugins directory.

Thanks for reporting - I'm not sure how it went unnoticed for so many years.
