### ISSUE TITLE
Undefined property: stdClass::$branch

### ISSUE THREAD

**Issue by lbailey-ucsf** [davosmith/moodle-checklist#127]
During a fresh install of Moodle 4.4.3, Checklist master branch, tag 4.1.0.2, throws "Undefined property: stdClass::$branch" on line 887 of mod/checkist/lib.php, effectively halting the install. 

The error occurs during a fresh 4.4.3 install of Moodle on the /user/editadvanced.php page. When installing Moodle 4.3.8 it's a warning. 

See screen shot for stack trace.

![Screenshot 2024-10-18 at 14-34-09 Whoops! There was an error](https://github.com/user-attachments/assets/d9361fc0-9dd5-4795-8e58-b73d243eb254)

![Screenshot 2024-10-18 at 10-13-12 This page should automatically redirect  If nothing is happening please use the continue link below  Moodle](https://github.com/user-attachments/assets/e45cf680-3a20-45c8-9f0c-aff4503802a6)

**Comment by davosmith** [comment]
That's a very strange error you're getting.

The $CFG->branch value has existed for a long time in Moodle core and, from a quick check through the code is still widely present in the code.

However, I've just done a clean install and can see the error locally.

I've stripped out all the obsolete $CFG->branch checks and will publish a new version of the plugin, once it's passed all the relevant tests.
