### ISSUE TITLE
Moodle 2.7 update_event() is deprecated

### ISSUE THREAD

**Issue by ruddj** [davosmith/moodle-checklist#30]
Hi Dave,
 Just testing on Moodle 2.7 and received this error when changing the activity name.
```
update_event() is deprecated, please use calendar_event->update() instead.
line 1756 of /lib/deprecatedlib.php: call to debugging()
line 2416 of /mod/checklist/locallib.php: call to update_event()
line 2438 of /mod/checklist/locallib.php: call to checklist_class->setevent()
line 110 of /mod/checklist/lib.php: call to checklist_class->setallevents()
line 548 of /course/modlib.php: call to checklist_update_instance()
line 266 of /course/modedit.php: call to update_moduleinfo()
```

**Comment by davosmith** [comment]
Thanks for spotting that - I'll try and fix that ASAP.

**Comment by ruddj** [comment]
Just to confirm it did appear to work correctly and the name was changed, it just generated this notice for changing it in calendar as well.
Thanks.

**Comment by davosmith** [comment]
I've just checked in a fix for this - please let me know if it works OK for you

**Comment by ruddj** [comment]
Thanks. I just checked and I am not seeing the warnings anymore.
