### ISSUE TITLE
Automatic update not fetching data in 2.8

### ISSUE THREAD

**Issue by CamBanfield** [davosmith/moodle-checklist#31]
The automatic update system doesn't work on 2.8 as it seems the plugin is only checking the legacy logs instead of the new standard logging system. 

A way around this is to enable both the legacy logs along side the new default logging system however this doesn't work flawlessly as SCORM packages are not checked off when accessed.

Moodle version: 2.8.5+ (Build: 20150326)
Plugin version: 2015050900

If you need any more information just let me know!
Thanks,

**Comment by davosmith** [comment]
This is a known problem and a fix has been created for a specific client - I am waiting on confirmation that I can release this fix.

Using the standard Moodle completion system continues to work, as an alternative.

**Comment by davosmith** [comment]
Just a note - the new version of the checklist plugin which was published today should fix this issue (although completion will only be re-calculated for a checklist if you turn off automatic updates for the checklist, save, then turn them back on again and save again).
