### ISSUE TITLE
Checklist module will not install in Moodle 3.0

### ISSUE THREAD

**Issue by ttsilva90** [davosmith/moodle-checklist#34]
Attempting to install the latest version (2015100200) of mod_checklist on a Moodle 3.0 site (3.0dev+ (Build: 20151020)) results in the following error:

Unsupported $module syntax detected in version.php of the mod_checklist plugin.
Plugin "mod_checklist" is defective or outdated, can not continue, sorry.
Debug info: Unsupported $module syntax detected in version.php
Error code: detectedbrokenplugin

**Comment by davosmith** [comment]
Thanks for the heads-up - it actually supports both the old and new syntax of version.php, but it looks like Moodle is being picky about it now. I'll try to put together a fix tomorrow.

**Comment by davosmith** [comment]
This is fixed in the latest version (now on Moodle.org and here)
