### ISSUE TITLE
Checklist-exporter needs to implement enclosing the checklist elements in single single or double quotes

### ISSUE THREAD

**Issue by KSLaring** [davosmith/moodle-checklist#37]
When a checklist item contains commas, e.g. "Make a list of ICT-systems - name, vendor, version", exporting the checklist works, but importing the exported checklist fails since the item contains commas. These are interpreted by the importer as information fields, and the importer complains about the wrong number of fields in the line it is trying to import from the CSV-file and stops.

I guess the solution is to include some form of delimiter when exporting, so the importer can distinguish information fields from a single field containing commas. 

It would be wise to document what kind of delimiter is expected if items do have commas, e.g. "Information fields containing strings with commas must be enclosed in CHARACTER_THAT_WORKS to successfully import the checklist".

Thanks for this otherwise great plugin!

**Comment by davosmith** [comment]
As is standard with CSV files, enclosing the elements in single or double quotes allows for commas to be present in the import.

I may not have implemented that during the export, but import certainly already handles that.

**Comment by KSLaring** [comment]
Thanks for the swift reply - looking forward to the update.

**Comment by davosmith** [comment]
I've just checked in a fix for this - can you test the latest version of the code for me, before I release to Moodle.org?

**Comment by KSLaring** [comment]
Sure, but I tried to download the master branch as ZIP, and Moodle complained the new version was older than the one I got -> current 2016052000 ->	new 2016030601.

**Comment by davosmith** [comment]
You might want to try again and make sure you are downloading from the master branch - if you look here https://github.com/davosmith/moodle-checklist/blob/master/version.php , you can see the version is 2016103000 (the same as what I get when I download the master branch).

**Comment by KSLaring** [comment]
This issue seems to be fixed - it is now possible to create list items with commas, export the list, then correctly import into a new list without errors. Thank you!
