### ISSUE TITLE
2nd tick deletes and substitutes a 0

### ISSUE THREAD

**Issue by ChristinaM2016** [davosmith/moodle-checklist#38]
Hello.   I am using the 2.9 version of Moodle/Totara and I just installed the checklist which is very neat by the way.  I have however, discovered a small bug in the software.   Sometimes-apparently randomly, when you tick the box to turn the line into a header, instead of bolding the words, it deletes your writing and substitutes a 0.     I have been dealing with this all of last week as I attempt to create different checklists in our system.

thanks
Christina

**Comment by davosmith** [comment]
Hi Christina,

I'm afraid you've not really given me very much information to go on - I've just had a quick go with my the latest version of my code, clicking lots of times on the icon you have indicated and every time it has worked exactly as expected.

I've also taken a quick look at the code and I can't see any obvious code path that would ever get from clicking that button to updating the text of the item (it just updates the relevant field in the database, leaving the rest of the details untouched).

I'm going to need some really clear, step-by-step instructions about how to consistently reproduce this problem before I have any chance of finding a fix for it. Next time it occurs, maybe you could add a screenshot, particularly showing the URL params when it happened?

**Comment by ChristinaM2016** [comment]
Hi. Thank you for your response.  I will try to capture it as you suggested-IF it happens again. (hopefully it wont)  Also, thanks so much for creating this checklist.  I believe it will be the solution that one of our department heads is looking for.   =)

Christina Morejon |  Learning Management Specialist
FARO | 125 Technology Park | Lake Mary, FL 32746
407-333-9911 ext. 1130| Fax 407-333-4181
Nasdaq: FARO | christina.morejon@faro.com<mailto:christina.morejon@faro.com> | www.faro.com<http://www.faro.com/>

**Comment by ChristinaM2016** [comment]
Unfortunately, I spoke to soon.   Video is here –due to size
https://www.screencast.com/t/jZhx0YkF68


thanks.
Christina Morejon |  Learning Management Specialist
FARO | 125 Technology Park | Lake Mary, FL 32746
407-333-9911 ext. 1130| Fax 407-333-4181
Nasdaq: FARO | christina.morejon@faro.com<mailto:christina.morejon@faro.com> | www.faro.com<http://www.faro.com/>

**Comment by davosmith** [comment]
I can't make out the full URL params in the video, after the button has been clicked on and the heading has turned into a 0. Please could you let me know what they were?

**Comment by ChristinaM2016** [comment]
Im sorry, I don’t understand what your asking for?

Christina Morejon |  Learning Management Specialist
FARO | 125 Technology Park | Lake Mary, FL 32746
407-333-9911 ext. 1130| Fax 407-333-4181
Nasdaq: FARO | christina.morejon@faro.com<mailto:christina.morejon@faro.com> | www.faro.com<http://www.faro.com/>

**Comment by davosmith** [comment]
When you clicked on the icon, I can see that the page this icon linked to was:
https://learn.faro.com/mod/checklist/edit.php?id=719&ses...

I need to know what the rest of the URL was.

**Comment by ChristinaM2016** [comment]
[cid:image001.jpg@01D29BEF.82BBCB00]

Christina Morejon |  Learning Management Specialist
FARO | 125 Technology Park | Lake Mary, FL 32746
407-333-9911 ext. 1130| Fax 407-333-4181
Nasdaq: FARO | christina.morejon@faro.com<mailto:christina.morejon@faro.com> | www.faro.com<http://www.faro.com/>

**Comment by davosmith** [comment]
I can't see the attachment.

**Comment by ChristinaM2016** [comment]
It wasn’t an attachment.  I screen shot the picture you needed.   But here is the information


https://learn.faro.com/mod/checklist/edit.php?id=719&sesskey=N745R8SfSI&itemid=322&action=makerequired

Christina Morejon |  Learning Management Specialist
FARO | 125 Technology Park | Lake Mary, FL 32746
407-333-9911 ext. 1130| Fax 407-333-4181
Nasdaq: FARO | christina.morejon@faro.com<mailto:christina.morejon@faro.com> | www.faro.com<http://www.faro.com/>

**Comment by davosmith** [comment]
OK - that has confirmed that the link is exactly was I would have expected it to be.

I can't see how that would result in the title of the checklist being changed - would it be at all possible for you to create a backup of that one activity, without any user data, and send it to me (you can email it to moodle@davosmith.co.uk if you prefer not attaching it to this public ticket)?

**Comment by davosmith** [comment]
Hi Christina - I've had a go with the backup you sent through.

I've also tried it specifically with Totara 2.9, using IE11 (as you appear to be using a version of Internet Explorer in the video and that is the only version I have to hand).

Nothing I've tried has managed to reproduce the problem or offer any clue as to what might be happening.

If you have a Totara site, then I'm guessing you might well have a support contract with the Totara Partner that sold it to you? In which case, they may be better placed to investigate this further. If you were a client of ours, I'd probably, at this point be taking a fully copy of your live database and trying to reproduce the issue locally, or, if that didn't work, introducing some logging into the plugin to try and trace exactly what is going wrong. Neither of those are things I'm able to do in this case.

This is the first time I've had any reports of issues like this (in the 7 years the plugin's been available), so I'm not really sure what else to suggest.

Sorry I can't be of more help than that.

**Comment by ChristinaM2016** [comment]
Hello Davo

I had a request from one of the dept heads using your checklist and he wanted to know if we could do this:

  *   Onboarding Checklist:
     *   If I were to click into “Item #30 SAP: INTERMEDIATE”, there are multiple things listed, Just clicking into it and clicking on one item checks it off when you go back to the main view of the checklist.
     *   Is there any way to control each item they do individually? For example, each of the following is an actionable item that would need to be completed for item #30 to be signed off on.
        *   [cid:image003.jpg@01D2A3E1.B1D87DD0]

Im testing the flow with this course https://learn.faro.com/mod/checklist/view.php?id=740

Each of the 5 items is linked either by url or course to a separate module.  The request was to make it so that the box in Item 31 shows complete only when ALL of the 5 boxes below are completed.  Does that make sense?   Here is a pic of the checklist: [cid:image004.jpg@01D2A3E2.B209AA80]

I believe that my settings are correct to make the list work the way we wanted it to , but its not working—here is a picture of the settings page: [cid:image002.jpg@01D2A3E2.9C127F40]

Do you have any insights you would be willing to share?  Does your checklist work in a way that I could configure it to do what our Dept Head wanted?

I really appreciate any information that you could provide.  Our vendor was stumped.

Christina Morejon |  Learning Management Specialist
FARO | 125 Technology Park | Lake Mary, FL 32746
407-333-9911 ext. 1130| Fax 407-333-4181
Nasdaq: FARO | christina.morejon@faro.com<mailto:christina.morejon@faro.com> | www.faro.com<http://www.faro.com/>

**Comment by davosmith** [comment]
Hi Christina,

The images you have included have not come through into github - please send me an email directly (moodle@davosmith.co.uk) if you want me to see them.

I'm not sure if I can follow the question without the images you are referring to.

Davo

**Comment by ChristinaM2016** [comment]
My apologies. I will redirect the email now to moodle@davosmith.co.uk<mailto:moodle@davosmith.co.uk>)
Thank you!
Christina Morejon |  Learning Management Specialist
FARO | 125 Technology Park | Lake Mary, FL 32746
407-333-9911 ext. 1130| Fax 407-333-4181
Nasdaq: FARO | christina.morejon@faro.com<mailto:christina.morejon@faro.com> | www.faro.com<http://www.faro.com/>
