### ISSUE TITLE
Function get_objectid_mapping() lacking

### ISSUE THREAD

**Issue by lucaboesch** [davosmith/moodle-checklist#42]
Upon performing a restore into Moodle 3.3 warnings are thrown:

In order to restore course logs accurately the event "mod_checklist\event\checklist_completed" must define the function get_objectid_mapping().
In order to restore course logs accurately the event "mod_checklist\event\student_checks_updated" must define the function get_objectid_mapping().
In order to restore course logs accurately the event "mod_checklist\event\course_module_viewed" must define the function get_objectid_mapping().

**Comment by davosmith** [comment]
Thanks for reporting this - I don't think I've ever run a backup with logs enabled, so I wasn't aware of this issue.

I've now fixed it on github and will include the fix in the version on Moodle.org next time I do a release (this is too minor an issue to warrant an extra release of its own).
