### ISSUE TITLE
add "Back to Course" button

### ISSUE THREAD

**Issue by dustinbrisebois** [davosmith/moodle-checklist#43]
Greetings - could we have a button added to the bottom of the view.php file which goes back to the originating course?

**Comment by davosmith** [comment]
That's not something that I'd add as standard to the checklist module - it would be inconsistent with the way that all other modules work and there are already links back to the course on the page (e.g. in the breadcrumb at the top of the page).

However, the code is all available, so you are welcome do make such a change with your local copy.
