### ISSUE TITLE
Mobile app support

### ISSUE THREAD

**Issue by jeremy-schweitzer** [davosmith/moodle-checklist#44]
Love the plugin - and so do many users, but recently I've gotten requests about support on mobile. Any plans to add support for the Moodle mobile app? Right now it's kicks users out to their mobile browser. 

https://docs.moodle.org/dev/Moodle_Mobile_Remote_add-ons

**Comment by davosmith** [comment]
Sounds like an interesting idea and something I'd like to find out how to do, but I'm not sure how much spare time I have to take on something like that (and it sounds like it might be at least a couple of days work). Is this something you have any funding to allow me to do this during my normal working day?
