### ISSUE TITLE
Email to Teacher = more than Teacher? 

### ISSUE THREAD

**Issue by wheelerda** [davosmith/moodle-checklist#45]
We have a number of users in administrative roles (at the system or course category levels) receiving Checklist student completion emails unexpectedly (they have nothing to do with the course). The Teacher had configured for Teacher to receive email upon completion.  **Email when checklist is complete: Teacher only**

I haven't had chance to dig into the issue, but since it appears related to (not the result of) the recent change for 'enrolled users' I'm posting this now. 

My guess 
Email when checklist is complete: Teacher only 
is not "Teacher only"

...dan wheeler

**Comment by davosmith** [comment]
The email is sent to all users with capability 'mod/checklist:emailoncomplete' in the context of the activity. By default, only the 'teacher' and 'editingteacher' roles have this capability.

If you have roles assigned at a higher level than at the course level (and you do not want those users to receive notifications), then you need to make sure those roles do not have the capability 'mod/checklist:emailoncomplete'.
