### ISSUE TITLE
each() function is deprecated in PHP 7.2

### ISSUE THREAD

**Issue by ewallah** [davosmith/moodle-checklist#48]
I receive 3 generalexceptionmessages running behat tests on a php 7.2 server:

```
001 Scenario: When viewing an auto-populated checklist, a student should see items corresponding to the course modules : mod/checklist/tests/behat/show_hide_multiple_items.feature:30

002 Scenario: When I select multiple items and click the 'Show/hide' button, the items' visibility should toggle : mod/checklist/tests/behat/show_hide_multiple_items.feature:40

003 Scenario: The checklist should always display the current items from the section, keeping up to date when they change.  : mod/checklist/tests/behat/completion.feature:47
```

```
Moodle exception: Exception - Unknown error type: The each() function is deprecated. This message will be suppressed on further calls in [dirroot]/mod/checklist/locallib.php on line 235
More information about this error
        Debug info:
        Error code: generalexceptionmessage
        Stack trace:
        line 158 of /lib/behat/lib.php: Exception thrown
        line ? of unknownfile: call to behat_error_handler()
        line 235 of /mod/checklist/locallib.php: call to each()
        line 119 of /mod/checklist/locallib.php: call to checklist_class->update_items_from_course()
        line 59 of /mod/checklist/view.php: call to checklist_class->__construct()
         (Exception)

```

**Comment by davosmith** [comment]
Thanks for the report - I'll try to look at this at some point, but not sure how much of a rewrite this will need (as the structure of the code currently strongly relies on the use of that function).

This is not a major priority, as only the very latest version of Moodle supports PHP 7.2 (so very few people are using it yet) and this is only a deprecation warning, so it does not (yet) have any effect on the actual functionality of the plugin. I will certainly get this fixed before Moodle requires PHP 7.2 or before the latest version of PHP removes the each() function.

**Comment by davosmith** [comment]
I've replaced the each() function calls with current() and next() calls - this should now work without warnings on PHP7.2 (but I don't have a local install of PHP7.2 to double-check).

**Comment by ewallah** [comment]
Seems to be fixed, THX

A free and fast way to double check multiple php versions (but also multiple browsers, branches and databases) is Travis: have a look at https://travis-ci.org/ewallah/moodle-checklist/jobs/345632236

You only have to 

1. create an account on travis-ci.org
1. give access to your github account
1. add a .travis.yml file  (like https://github.com/ewallah/moodle-checklist/blob/master/.travis.yml)
1. trigger a build

**Comment by davosmith** [comment]
Thanks - I'm aware of Travis, but I've never got around to figuring out how to format a travis.yml file.
