### ISSUE TITLE
backup/restore/import/export URL's stripped

### ISSUE THREAD

**Issue by Syxton** [davosmith/moodle-checklist#49]
If a manual checklist item is created with a URL the export/import and backup/restore/import strip the URL's from these items.  MAJOR issue!

**Comment by davosmith** [comment]
Hi Syxton - melodramatic use of capital letters to declare this is a MAJOR issue won't get it fixed any quicker (especially as it can't be that major an issue, if it has taken 18 months for anyone to notice).

Looks like I simply missed adding the new fields to the backup script - should be, fixable very quickly once I'm back in my dev environment.

If this is causing you problems, then feel free to add the missing 'linkcourseid' and 'linkurl' fields to your local copy here: https://github.com/davosmith/moodle-checklist/blob/master/backup/moodle2/backup_checklist_stepslib.php#L44

**Comment by Syxton** [comment]
It is also missing from the built in export import csv.  Sorry for appearing melodramatic with capital letters.

**Comment by Syxton** [comment]
If it helps I made a pull request #49

**Comment by davosmith** [comment]
I looked at this in a bit more detail - for safety I've extended the backup + restore slightly so that linkcourseid is cleared when restoring to a different site.

I've also reworked the import/export script so that as well as adding the new fields it also copes with the fields not being present (to avoid breaking all existing exports).

Could you check that this all works for you, before I look at pushing this out to Moodle.org?

**Comment by Syxton** [comment]
@davosmith Ok I have tested and am running into a few issues.
My test setup: Moodle 3.5dev (Build: 20180104)
Course setup: Course A, Course B
Course A:  checklist showing all course activities, 2 manual items with urls.  The first manual link was external url of google.com, the second link was the URL of an assignment inside the course.

I did a moodle import of the checklist and all the activities.
The problem I see:
1.  The manual URL to the activity is converted during backup but not restored.  Looks like "http://localhost/work/moodle35/mod/checklist/$@ASSIGNVIEWBYID*7@$".  In the database it just has $@ASSIGNVIEWBYID*7@$

I then did a checklist export from Course A and checklist import to Course B
The list shows as expected, with all moduleid links removed and all manual links exactly as they were in Course A.

**Comment by Syxton** [comment]
@davosmith Another issue I see (and it is unrelated, so I should probably make a new issue) but when I deleted activities from the course, they were not removed from the checklist.

**Comment by davosmith** [comment]
@Syxton Really sorry for the lack of response - I've had a major computer failure on my main desktop, that I'm still trying to recover from, so I'm not quite up to speed again on my Moodle dev. I'll try to address these issues soon.

**Comment by davosmith** [comment]
@Syxton I've had a look at the code for this and implemented 2 fixes:
* Links to course activities that were manually added to items are now restored correctly from backup
* Items linked to activities that were pending deletion (ready to go in the recycle bin) are now removed from the checklist (I can see this as something I may well have to fix in other developments I've done over the years).

Please can you check that these issues are now fixed for you?

**Comment by Syxton** [comment]
This seems to be working as expected.

**Comment by davosmith** [comment]
Thanks - closing the ticket.
