### ISSUE TITLE
Filter View Progress by group (both viewing and editing/checking off)

### ISSUE THREAD

**Issue by tracswa** [davosmith/moodle-checklist#51]
For teacher, on the "View Progress" tab, finding the appropriate students in a large list is difficult. It would be good to filter by group to both see student progress and tick off students in that group.

Optionally it would also be good to change the number of students shown per page in the settings.

**Comment by tracswa** [comment]
Also thanks great plugin!

**Comment by davosmith** [comment]
Filtering by group has always been a feature of this plugin, as long as the checklist activity is set to 'visible groups' or 'separate groups' mode, if you set it to 'no groups', then filtering by groups is not possible.

Whilst there is no UI for it, if you manually add '&perpage=60' to the page params, then you will see 60 students per page (but only this time) - you can use any number you like here.

**Comment by scara** [comment]
Hi @tracswa,
you could even open a new issue since you've narrow down the issue when using a 3rd party theme, which could badly interfere w/ the original design.

**Comment by davosmith** [comment]
Hi @tracswa - I'm afraid I can't really work around 3rd-party themes doing bad things with standard Moodle output (from memory, I'm not doing anything non-standard with the group selector).

I suggest you raise a ticket against the Essential theme and see if there is a good reason why they are hiding the 'group selector' (this would, I assume, affect every activity that uses a group selector).

**Comment by tracswa** [comment]
It looks like the CSS responsible is actually custom CSS our contractor put into the theme, so apologies for the distraction. Unfortunately for me, removing that style unhides groupselector in other parts of the site where its a problem, and the tag classes/ids make it difficult to apply styles to one but not the other, but that's my problem to solve! Thanks for your help guys!

**Comment by tracswa** [comment]
(solution - use activity specific id in the <body> tag)

**Comment by davosmith** [comment]
Glad to hear you got to the bottom of it and the plugin is now working as you wanted.
