### ISSUE TITLE
Moodle 3.4: Activities and ressources are added even if completion tracking not activated

### ISSUE THREAD

**Issue by dasistwas** [davosmith/moodle-checklist#52]
In a course completion tracking is enabled, but not all activities and resources have completion tracking enabled. The checklist should only add items which have completion tracking enabled. But in Moodle 3.4 nearly everything is added no matter if completion tracking is enabled or not. Setting: Check-off when modules complete -> Yes, can not override.

# How to reproduce

- In a course with many activities and resources add the checklist module
- Use settings from attached screenshot
- Save checklist
- Result: All activities resources are added to the checklist even if the completion tracking is not activated for the resources or activities

Expected behaviour: Only activities and resources with completion tracking enabled should be added as item to the checklist.

![screenshot-2018-3-22 editing checklist](https://user-images.githubusercontent.com/1620975/37783052-c559bfa6-2df4-11e8-9ac7-3aa8389e095e.png)

**Comment by davosmith** [comment]
This is the correct behaviour.

The checklist imports a list of all activities from the course (or section), it does not restrict these based on whether or not completion is enabled (either for the course or for individual activities). If you wish to exclude certain activities from a checklist, then you can hide them on the checklist editing page.

If 'automatic update' is enabled and completion is enabled for the linked activity, then completing that activity will automatically update the checklist item. If completion is not enabled for that activity, then there are a number of custom rules that apply (e.g. assignment submitted, forum post created, etc.) which allow those checklist items to be automatically updated.
