### ISSUE TITLE
Editing checklist item with date removes date.

### ISSUE THREAD

**Issue by Syxton** [davosmith/moodle-checklist#53]
If Date Editing mode is not turned on, and a user edits a checklist item that had already been given a date, the date is removed upon update. 

I propose that if you edit a checklist item that contains a date, the date editor will automatically be enabled.

**Comment by Syxton** [comment]
@davosmith Removing the editmode all together might also be an option.  Just an idea.  Thanks

**Comment by davosmith** [comment]
Editing an item with a date, whilst date editing is off, no longer removes the existing date.
