### ISSUE TITLE
Minimum requires value should not to be updated with each new release

### ISSUE THREAD

**Issue by logan-reynolds** [davosmith/moodle-checklist#57]
We're seeing that the minimum requires value in version.php appears to be updated with each new release, which causes problems when plugins are automatically updated to the newest version because it requires an immediate upgrade of the site just to get the checklist plugin updated.  In general this value should be set at it's default lowest value for the earliest version of each branch (i.e. 2017111300 for M3.4 and 2018051700 for M3.5 per https://docs.moodle.org/dev/Releases), unless the plugin depends on some specific functionality that is only available in the latest Moodle release.

**Comment by davosmith** [comment]
I have only updated the minimum requires value for the checklist plugin where this has been necessary. Most recently this has been done to support privacy API functionality only found in Moodle 3.4.6, Moodle 3.5.3 and Moodle 3.6.

Could you give a specific example of a commit where I have incremented the requires version, without needing to?

**Comment by davosmith** [comment]
As far as I am aware, the times I have incremented this value were:
* When I dropped compatibility with Moodle versions below 2.7
* When I dropped compatibility with Moodle versions below 3.4 (privacy API)
* When I dropped compatibility with Moodle versions below 3.4.6 (privacy API).

**Comment by davosmith** [comment]
As I've not heard anything further on this, I'm going to close this ticket.
