### ISSUE TITLE
Update supposedly requires Moodle 201711306 but won't install in Moodle 3.5+ (Build: 20180614)

### ISSUE THREAD

**Issue by germanvaleroelizondo** [davosmith/moodle-checklist#58]
Hi,

I attempted to upgrade several plugins for my Moodle 3.5+ (Build: 20180614) server.

Moodle checklist could not be updated as it ultimately asked me to upgrade to Moodle 3.5.3

The plugin current version states "3.4+ (Build: 2018051500) (2018051500)Moodle 3.4, 3.5, 3.6"

During plugin installation, validation results checked for Moodle 201711306.

Can you please sort this.

Thanks in advance.

![mod_checklist_must upgrade to moodle 3 5 3 or above l](https://user-images.githubusercontent.com/2671923/50780577-e9356480-1268-11e9-896f-c601a7e60434.png)

![mod_checklist_validation successful](https://user-images.githubusercontent.com/2671923/50780587-edfa1880-1268-11e9-8d40-5809ab395ffa.png)

![mod_checklist_upgrade available](https://user-images.githubusercontent.com/2671923/50780595-f2263600-1268-11e9-864b-ce2f37ea6f04.png)

**Comment by davosmith** [comment]
Moodle made a change to the privacy API in Moodle 3.4.6 and 3.5.3.

The latest version of the checklist plugin has been updated to match the requirements of this change.

I would advise you to update to Moodle 3.5.3 or above, as this will include the latest security fixes. If that is not possible, then please download the previous version of the checklist plugin, which is compatible with Moodle 3.5.0-3.5.2.

**Comment by germanvaleroelizondo** [comment]
I will.

Thanks Davo.

**Comment by davosmith** [comment]
FYI - version 2018042100 from here: https://moodle.org/plugins/pluginversions.php?plugin=mod_checklist will work fine.

To be clear, this is a one-off issue that has been caused by a decision by Moodle HQ to introduce a non-backwards compatible API change in a minor release and which I hoped would affect very few people (on the assumption that anyone keen enough to keep their plugins up to date would also keep their main code up to date as well).

**Comment by germanvaleroelizondo** [comment]
Unfortunately, Updating the Moodle version is not as easily made as updating a plugin from the web interfase. 

I (like many more Moodle teachers/admins) will need to convince the IT guys at my University.
