### ISSUE TITLE
Importing checklist into new course changes custom item dates incorrectly

### ISSUE THREAD

**Issue by ebithell** [davosmith/moodle-checklist#61]
We've found an issue with importing checklists from one course into another where dates are set against custom checklist items. It's easiest to explain with an example using specific dates, and then the example is easily generalised.
Steps to reproduce:
1. Create a course (A) with start date 18-May-2019
2. Add a checklist activity (C1) to course A
3. Add a custom checklist item (CC1) with an expected date of 27-May-2019
4. Create a second course (B) with start date 20-May-2019
5. Import the checklist created in step 2 (C1) from course A into course B to automatically create a new checklist activity C2 with custom checklist item CC2
Expected result:
(a) The custom checklist item CC2 has an expected date of 29-May-2019 i.e. shifted by 2 days from CC1, the same as the increment between the course start dates from A to B
OR
(b) The custom checklist item CC2 has an expected date of 27-May-2019 i.e. the same as CC1.
I believe that (a) is preferable because this is the same as the behaviour of other date-specific modules e.g. Assignment, but others might argue differently.
Actual result:
The custom checklist item CC2 has an expected date of 31-May-2019 i.e. double the increment between the course start dates from A to B. I assume that the same would happen with backup/restore if the course start date was modified, but haven't tested this.
I haven't been able to track down exactly what is causing this, but thought I should log the issue so that others are aware of it.

**Comment by davosmith** [comment]
Finally had a spare moment to investigate this - wrote an automated test to reproduce cleanly and then fixed it.

The actual fix was very simple - I'd simply called the date offset function twice (so I deleted one of them).

Fixed on github, will roll out to Moodle plugins list at some point.

**Comment by ebithell** [comment]
Many thanks - we will be pleased to pick up the fix when we next upgrade this plugin.
