### ISSUE TITLE
requesting new release

### ISSUE THREAD

**Issue by stopfstedt** [davosmith/moodle-checklist#69]
Hi Davo,
Just wanted to respectfully request a new release, please let me know if I can help out in any way in order to expedite this (reviewing PRs, maybe fix a few of the outstanding issues). 
Thanks!
- Stefan

**Comment by davosmith** [comment]
Hi Stefan,

Why are you wanting a new release of my checklist plugin?

There are no important bugs that I'm aware of.
There are no new features that have been developed, which are awaiting release.
The plugin already works with the latest version of Moodle.

What else were you expecting from a new release?

**Comment by stopfstedt** [comment]
Hey, thanks for the quick reply.
I'm after this functionality: https://github.com/davosmith/moodle-checklist/pull/68
I can't push `master` into our production system, since I'm bound by policy to only ship tagged/"released" plugins.
Hence my request for a version bump/new release.

**Comment by davosmith** [comment]
OK - I'm on the wrong computer right now, so I can't make changes. I'll take a look at pushing out to the Moodle plugins DB tomorrow (normally, I just wait for the next Moodle release to send out updates).

**Comment by stopfstedt** [comment]
Much appreciated!
