### ISSUE TITLE
Installing via composer version error

### ISSUE THREAD

**Issue by bejes** [davosmith/moodle-checklist#76]
Trying to install the correct version for moodle 3.8
Assume it's `"moodle-plugin-db/mod_checklist": "2020012900"`
However composer complains with
`Problem 1
    - Installation request for moodle-plugin-db/mod_checklist 2020012900 -> satisfiable by moodle-plugin-db/mod_checklist[2020012900].
    - moodle-plugin-db/mod_checklist 2020012900 requires moodle/moodle 3.9.* -> satisfiable by moodle/moodle[v3.9.0, v3.9.0-beta, v3.9.0-rc1, v3.9.0-rc2, v3.9.0-rc3, v3.9.1, v3.9.2, v3.9.3, v3.9.4] but these conflict with your requirements or minimum-stability.`
  This seems to conflict with the version listed https://moodle.org/plugins/pluginversions.php?plugin=mod_checklist which states the correct version for 3.9 is 2020111400.
Any advice on how to resolve this conflict? 
https://moodleplugarit.mmg.fi/search?q=checklist&moodle_version=3.8&search= reports that the version can be 2019111500 or 2020012900? However given i have installed 2020012900 moodle throws an exception if I try to install the earlier version.
Thanks

**Comment by davosmith** [comment]
Hi bejes,

Moodle does not support plugin installation via composer and neither does my checklist plugin.

There was a version of the plugin, with version number 2020012900 that was released for Moodle 3.9 only - this only differed from the Moodle 3.4 version (with the same version number) due a minor change in the automated testing (as far as I remember) - the changes did not affect the end user at all. As a result, I was not aware of any reason to change the version number. I will try to avoid this happening again in the future, but I do not intend to publish an extra version of the plugin, simply to fix an unsupported installation method (particularly given this only affects Moodle 3.8, which is on 'security fix only' and will be completely unsupported in a couple of months time).

Please download the correct version of the plugin here: https://moodle.org/plugins/pluginversions.php?plugin=mod_checklist
