### ISSUE TITLE
Missing in AMOS

### ISSUE THREAD

**Issue by dinism** [davosmith/moodle-checklist#79]
Sorry for asking.
Do you know why last updated/added strings in lang file are missing in AMOS?
Is a AMOS issue?
For example:

$string['completiondetail:percent'] = 'Check-off items: {$a}%';
$string['completiondetail:items'] = 'Check-off items: {$a}';
$string['showcolorchooser'] = 'Display color chooser';
$string['showcolorchooserdesc'] = 'Displays the color chooser of the list elements in edit.php';

Thanks

**Comment by davosmith** [comment]
Hi @dinism 

I'm not really sure - I can't see any reason why those new language strings wouldn't have pulled through.

I've send David Mudrak a message via Moodle.org and I'll see if he has any idea.

**Comment by dinism** [comment]
They are TRANSLATED!
