### ISSUE TITLE
Request: Please add git release tags to repository

### ISSUE THREAD

**Issue by danowar2k** [davosmith/moodle-checklist#80]
It would be very helpful for automatic deployment if you could add the git tags for each release you're doing.

Here are the commands to add the tags for two releases on moodle.org we're currently upgrading from and to, just as examples:

```
# Add tag for 3.4+ (Build: 2019061900) (https://moodle.org/plugins/mod_checklist/3.4-build-2019061900/20135)
# Note: Maybe you have to leave out whitespaces, colon or other symbols
git tag -a "3.4+ (Build: 2019061900)" 384a3657657c0c47743f777d6ec1b7d4549f1396 -m "ADDITIONAL_OPTIONAL_INFO"
# Add tag for 3.9+ (Build: 2021051500) (https://moodle.org/plugins/mod_checklist/3.9-build-2021051500/24175)
# Note: Maybe you have to leave out whitespaces, colon or other symbols
git tag -a "3.9+ (Build: 2021051500)" 83a197f54c9910745fd8341cd0f7a3c4e43bac07 -m "ADDITIONAL_OPTIONAL_INFO"
```

**Comment by davosmith** [comment]
I'll consider adding tags to future releases, if I remember, but I can't make any promises, as there are already quite a few steps to go through with each release.

The latest released version is always available in the Moodle plugins directory (which it should be possible to automatically download). The latest version on here is usually also stable, as any problems are usually caught by automated tests within a few minutes of them occurring.

**Comment by danowar2k** [comment]
Side note: I think there's an effort being done of automating moodle.org plugin releases when adding github tags. https://github.com/moodlehq/moodle-plugin-release
