### ISSUE TITLE
Divide by zero warnings after restoring a course backup with a checklist activity

### ISSUE THREAD

**Issue by lexxkoto** [davosmith/moodle-checklist#81]
Moodle version: 3.11+ (Build: 20210625)
Checklist version: 2021061200

When restoring an MBZ that contains a checklist activity, then navigating to the newly-restored course, the following debugging warning is printed to the screen repeatedly:

**Warning:** Division by zero in **mod/checklist/classes/completion/custom_completion.php** on line **60**

Navigating to the checklist activity, choosing 'Edit Checklist', then navigating away from that page without making any changes causes the warnings to disappear.

I can supply an MBZ file without any user data if you need something to poke about at.

![checklist-div-zero-warnings](https://user-images.githubusercontent.com/7327138/123819508-be846e00-d8f1-11eb-928c-5f0be1367224.jpg)

**Comment by davosmith** [comment]
I've pushed a fix - I've not tested it yet, but it should be OK.

Please could you pull the latest code from here and let me know if it sorts the problem.

**Comment by lexxkoto** [comment]
Resolved
