### ISSUE TITLE
Introduction is shown twice in Moodle 4.0

### ISSUE THREAD

**Issue by noisyjerm** [davosmith/moodle-checklist#98]
The introduction / description is shown above and below the heading on the view.php screen.
Version 3.9.1.2 (2022012200)

![checklist](https://user-images.githubusercontent.com/436184/191141544-11739bbb-5b8f-4f0a-9dc4-56880b271b01.jpg)

**Comment by davosmith** [comment]
This was fixed a while back, so closing the ticket.
