### ISSUE TITLE
Behat failure on "the_following_items_are_checked_off_in_checklist_for_user"

### ISSUE THREAD

**Issue by sharpchi** [davosmith/moodle-checklist#99]
If you run the "When a checklist with existing grades has an item switched to required, the grades are updated" scenario in "create_edit_checklist.feature" you get an exception on "And the following items are checked off in checklist..."
In the function for this step: "the_following_items_are_checked_off_in_checklist_for_user", you're checking that the values are in the $studentmarkmap or $teachermarkmap in lines 203 and 206.
These checks should be on the keys of the map vars.
i.e.
```
if (!in_array($update['studentmark'], array_keys($studentmarkmap))) {
    throw new Exception('Invalid studentmark value \''.$update['studentmark'].'\' in checklist update');
}
if (!in_array($update['teachermark'], array_keys($teachermarkmap))) {
    throw new Exception('Invalid teachermark value \''.$update['teachermark'].'\' in checklist update');
}
```

Moodle 4.0.3. PHP 8.0. Master branch on your plugin.

**Comment by sharpchi** [comment]
This is a change in PHP 8.0 and in_array(): https://www.php.net/manual/en/function.in-array.php
If you run the following, you get different results depending on the PHP version:
```
<?php

$studentmarkmap = array(
    'yes' => 1,
    'no' => 0,
);
$update['studentmark'] = 'yes';
if (!in_array($update['studentmark'], $studentmarkmap)) {
    echo "no";
} else {
   echo "yes";
}

?>
```

**Comment by davosmith** [comment]
Thanks for the report - I'll try to take a look at it as soon as possible, but I've not yet started running any Moodle code against PHP 8.0, so it may take a couple of weeks before I have a chance to review.

**Comment by sharpchi** [comment]
That's ok. I'm getting in early for next summer! Though it's got me thinking there could be lots of hidden bugs in Moodle in general with this very subtle change.

**Comment by davosmith** [comment]
Thanks for the report - from what I can see, I have absolutely no idea why this ever worked in the first place; the code is just plain wrong!

I've pushed a fix (array_key_exists(), rather than in_array()) and adjusted the github actions to test the M4.0 version against PHP 8.0.

Fingers crossed this will all work.

**Comment by davosmith** [comment]
Thanks again - closing this ticket as all working with PHP 8.0 (and github actions has been updated to automatically test against PHP 8.0 in the future).
